### ISSUE TITLE
it keeps saying server error when i try to connect to my server

### ISSUE THREAD

**Issue by QMAX5** [edencomputing/attprefabulator#28]

**Comment by TwidgeVR** [comment]
Can you provide more details about your issue?  A screenshot of the error message would be helpful, for example.

Please note if you are playing on a quest server they are not yet supported by Prefabulator.

**Comment by daddydemonix** [comment]
Im having a similar issue, during the set up process
![image](https://user-images.githubusercontent.com/45902191/127010952-da6be760-b7b7-4358-940a-a99116d20f04.png)

**Comment by QMAX5** [comment]
Sorry i did not know it did not work for quest servers. have a nice day.
