### ISSUE TITLE
will not load into server

### ISSUE THREAD

**Issue by Azlar054** [edencomputing/attprefabulator#34]
I do not know if this has anything to do or not but I am on the oculus quest 2. If the prefabulator does not work with quest 2 server please let me know. Anyway I can log into the ATT thru prefabulator just fine, I select my server making sure its blue and click connect, the screen does its "connecting" thing then goes right back to ATT login. I just downloaded the latest version from your site

**Comment by TwidgeVR** [comment]
Sorry, prefabulator does not work on quest servers at this time.
