### ISSUE TITLE
Cannot delete moulds spawned via the Prefabulator

### ISSUE THREAD

**Issue by DawnShadow** [edencomputing/attprefabulator#5]
Description: Cannot delete moulds via prefabulator

Reproduction Steps: Spawn a bunch of moulds, delete them all.

Server: A new Era

Time: 5:33 pm

Discord Username: DawnShadow#3429

**Comment by edencomputing** [comment]
Sorry for very slow response.  I've run into this one occasionally too, but I don't think it's a prefabulator issue.  Every once in a while when you change something via the API it doesn't get updated to the 'live' part of the server, and appears to be stuck and unselectable.  

You should be able to select them again if you re-log, and sometimes leaving and reentering the chunk will reload them.
