### ISSUE TITLE
1.6.2 update

### ISSUE THREAD

**Issue by parzival62** [edencomputing/attprefabulator#9]
hello, I am contacting you about the prefabulator application. since the 1.6.2 update I can no longer move the object, furniture, structure that I reveal, do you have a solution or an update?
thank you

**Comment by edencomputing** [comment]
If you are using Oculus, click the movement icons with the A button instead of trigger.

**Comment by parzival62** [comment]
j'ai essayé et ça fonctionne merci pour ta rapidité de réponce

**Comment by TwidgeVR** [comment]
Just an update that touch support has been implemented, which should also correct Oculus Touch trigger presses.  I'm closing this ticket but please let me know if you continue to have issues.
